### ISSUE TITLE
No .wav file is generated

### ISSUE THREAD

**Issue by saurabhvyas** [JuliusKunze/speechless#1]
I have downloaded english model and placed it in appropriate directory , I can see that model loads successfully , and audio input is working , but it never ends , it keeps detecting background sounds and still doesnt generate any .wav file , I have to manually press ctrl ^ c to stop it after few minutes .

**Comment by juliuskunze** [comment]
Hi! Please update to the new version. You can now customize noise thresholds and silence duration until termination, e. g. `record_plot_and_save(Recorder(silence_threshold_for_unnormalized_audio=.1, silence_until_terminate_in_s=1))`

**Comment by saurabhvyas** [comment]
Okay this issue has been fixed but still there is no text output produced , Also I only see .wav files generated and no spectrograms .

**Comment by juliuskunze** [comment]
Did you adjust the threshold to your mic? Did you call `wav2letter.predict`? Spectrogram should be in the same folder as generated .wav file.

**Comment by saurabhvyas** [comment]
![image](https://user-images.githubusercontent.com/6899784/27254781-6550f4f8-537f-11e7-80e2-651d5b7cbfe6.png)

Yes I did use predict method and , I saw in the folder there are 2 .wav files but no spectrogram

**Comment by saurabhvyas** [comment]
Also I did adjust parameters according to my mic , tried playing with them but no effect

**Comment by saurabhvyas** [comment]
Any update on this ?
